sudo: required
dist: trusty
language: cpp

matrix:
  include:
    - compiler: clang
      addons:
        apt:
          packages:
            - uuid-dev
      env:
        - COMPILER=3.7 LLVM_VERSION=3.7.1 BUILD_TYPE=Debug
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - uuid-dev
      env:
        - COMPILER=3.7 LLVM_VERSION=3.7.1 BUILD_TYPE=Release
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - uuid-dev
      env:
        - COMPILER=3.8 LLVM_VERSION=3.8.0 BUILD_TYPE=Debug
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - uuid-dev
      env:
        - COMPILER=3.8 LLVM_VERSION=3.8.0 BUILD_TYPE=Release
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - uuid-dev
      env:
        - COMPILER=5 BUILD_TYPE=Debug
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - uuid-dev
      env:
        - COMPILER=5 BUILD_TYPE=Release
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - uuid-dev
      env:
        - COMPILER=6 BUILD_TYPE=Debug
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - uuid-dev
      env:
        - COMPILER=6 BUILD_TYPE=Release
    - compiler: clang
      os: osx
      env:
        - BUILD_TYPE=Debug
      osx_image: xcode7.3
    - compiler: clang
      os: osx
      env:
        - BUILD_TYPE=Release
      osx_image: xcode7.3

before_install:
  ############################################################################
  # All the dependencies are installed in ${TRAVIS_BUILD_DIR}/deps/
  ############################################################################
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR}/local
  - cd ${DEPS_DIR}
  - export CXXFLAGS="-isystem ${DEPS_DIR}/local/include"
  - export PKG_CONFIG_PATH=${DEPS_DIR}/local/lib/pkgconfig
  - export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${DEPS_DIR}/local/lib"
  - export LDFLAGS="-L${DEPS_DIR}/local/lib"

  ############################################################################
  # Install a recent CMake
  ############################################################################
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="http://www.cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${DEPS_DIR}/cmake/bin:${PATH}
    fi

  - |
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      brew install cmake asio
    fi

  ############################################################################
  # Install clang on linux
  ############################################################################
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" && "${CXX}" == "clang++" ]]; then
      travis_retry wget --quiet -O - http://llvm.org/releases/${LLVM_VERSION}/clang+llvm-${LLVM_VERSION}-x86_64-linux-gnu-ubuntu-14.04.tar.xz | tar --strip-components=1 ${TAR_FLAGS} -xJ -C ${DEPS_DIR}/local

      export PATH=${DEPS_DIR}/local/bin:${PATH}
      export LDFLAGS="${LDFLAGS} -lc++ -lc++abi -lm"
      export CXXFLAGS="${CXXFLAGS} -isystem ${DEPS_DIR}/local/include/c++/v1 -stdlib=libc++"
      export CXX="clang-${COMPILER}" CC="clang-${COMPILER}"
      ${CXX} -v
    fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-${COMPILER}" CC="gcc-${COMPILER}"; fi

install:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      wget http://downloads.sourceforge.net/project/asio/asio/1.10.6%20%28Stable%29/asio-1.10.6.tar.bz2
      wget https://raw.githubusercontent.com/dirkvdb/doozy/develop/dependencies/asio/gcc.patch
      tar xf asio-1.10.6.tar.bz2
      patch -p1 < gcc.patch
      cd asio-1.10.6 && && patch -p1 < ../gcc.patch && autoreconf --force --install && ./configure --disable-dependency-tracking --without-boost --without-openssl --prefix=${DEPS_DIR}/local --disable-shared && make -j4 && make install
    fi
  - cd ${TRAVIS_BUILD_DIR}

before_script:
  - git clone -b develop --single-branch --recursive https://github.com/dirkvdb/utils.git ../utils

script:
  - git submodule update --init --recursive
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DSTANDALONE=ON .
  - make -j4
  - CTEST_OUTPUT_ON_FAILURE=1 make test

after_failure:
  - cat Testing/Temporary/LastTest.log
